spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: hello123
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #5minutes
    refreshTokenExpiration: 604800


server:
  port: 8081
