spring:
  application:
    name: store


  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #5minutes
    refreshTokenExpiration: 604800

  profiles:
    active: dev

  #security:
   # user:
   #   name: user
    #  password: hello123



#server:
 # port: 8081

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

websiteUrl: http://localhost:4242
