spring:
  datasource:
    url: ${SPRING_DATASOURCE_URI}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  #security:
   # user:
   #   name: user
    #  password: hello123

#server:
  #port: 8081
server:
  port: ${PORT}


websiteUrl: https://mystore.com


