spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  #security:
   # user:
   #   name: user
    #  password: hello123

#server:
  #port: 8081
server:
  port: ${PORT:8081}
  address: 0.0.0.0    # Bind to all interfaces


websiteUrl: https://mystore.com


