spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: MyPassword!
  jpa:
    show-sql: true


  flyway:
    baseline-on-migrate: true
    baseline-version: 5
    #security:
   # user:
   #   name: user
    #  password: hello123

server:
  port: 8081

websiteUrl: http://localhost:4242
